name: Cpp CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: git
        run: git --version
      - name: configure
        run: sudo apt-get install make cmake build-essential
      - name: gtest
        run: | 
          sudo apt-get install libgtest-dev
          cd ${{github.workspace}} 
          mkdir lib
          cd lib
          git clone https://github.com/google/googletest.git 
          cd googletest  
          mkdir build 
          cd build 
          cmake ../  
          make
      - name: build
        run: | 
          cd ${{github.workspace}} 
          mkdir build
          cd build 
          cmake ../ 
          make
      - name: test
        run: | 
          cd ${{github.workspace}}/build 
          ctest --output-on-failure
