name: Cpp CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: git
        run: git --version
      - name: configure
        run: |
          sudo apt-get update && sudo apt-get install make cmake build-essential clang-tidy clang-format libomp-dev doxygen
          pip3 install sphinx
          pip3 install breathe
          pip3 install pydata-sphinx-theme
          pip3 install sphinx-sitemap
          pip3 install semgrep
      - name: gtest
        run: | 
          sudo apt-get update && sudo apt-get install libgtest-dev
          cd ${{github.workspace}} 
          mkdir lib
          cd lib
          git clone https://github.com/google/googletest.git 
          cd googletest  
          mkdir build 
          cd build 
          cmake ../  
          make
      - name: build and test
        run: | 
          cd ${{github.workspace}} 
          mkdir -p build
          cd build 
          cmake ../ 
          make
          ctest --output-on-failure
      - name: lint (clang-tidy)
        run: |
          clang-tidy --extra-arg-before=-xc++-header src/*.cpp include/*.hpp include/detail/*.tpp -- -std=c++17
     - name: semgrep
        run: |
          semgrep scan --config .semgrep/rules/ src/ include/ test/
      - name: build docs
        run: |
          cd docs_sphinx
          make html
          cd _build/html
          touch .nojekyll
      - name: deploy docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs_sphinx/_build/html
